package com.CS5500.springbootinfrastructure.dao;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

public class Activity_helper {

    private Integer act_id; //autogenerated
    //public for parsing
    public String activity;

    public String group;
    public Boolean manual;
    public String startTime;
    public String endTime;
    public Float duration;
    public Float distance;
    public Integer steps;
    public Integer calories;
    public String[] trackPoints; //usually empty, not useful

    public Date last_update; //might not be useful to extract

    //can be used to load in database
    private Date start_time;
    private Date end_time;


    public String getGroup() {
        return group;
    }

    public void setGroup(String group) {
        this.group = group;
    }

    public Boolean getManual() {
        return manual;
    }

    public void setManual(Boolean manual) {
        this.manual = manual;
    }

    public Date getStart_time() {
        return start_time;
    }

    public void setStart_time(String start_time1) {
        DateFormat format = new SimpleDateFormat("yyMMdd'T'HHmmssZ");
        if (start_time1 == null){
            this.start_time = null;
            return;
        }
        try {
            this.start_time = format.parse(start_time1);
        } catch (ParseException e) {
            e.printStackTrace();
        }
    }

    public Date getEnd_time() {
        return end_time;
    }

    public void setEnd_time(String end_time1) {
        DateFormat format = new SimpleDateFormat("yyMMdd'T'HHmmssZ");
        if (end_time1 == null){
            this.end_time = null;
            return;
        }
        try {
            this.end_time = format.parse(end_time1);
        } catch (ParseException e) {
            e.printStackTrace();
        }
    }

    public Float getDuration() {
        return duration;
    }

    public void setDuration(Float duration) {
        this.duration = duration;
    }

    public Float getDistance() {
        return distance;
    }

    public void setDistance(Float distance) {
        this.distance = distance;
    }

    public Integer getCalories() {
        return calories;
    }

    public void setCalories(Integer calories) {
        this.calories = calories;
    }

    public Integer getSteps() {
        return steps;
    }

    public void setSteps(Integer steps) {
        this.steps = steps;
    }

    public Date getLast_update() {
        return last_update;
    }

    public void setLast_update(Date last_update) {
        this.last_update = last_update;
    }
}


