package com.CS5500.springbootinfrastructure.controller;


import com.CS5500.springbootinfrastructure.dao.DateLog;
import com.CS5500.springbootinfrastructure.repos.DateLogRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import java.sql.Date;

@Controller // This means that this class is a Controller
@RequestMapping(path="/activitydb") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private DateLogRepository dateLogRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewDateLog (@RequestParam Date dateOf
            , @RequestParam Integer caloriesIdle) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        DateLog n = new DateLog();
        n.setDate(dateOf);
        n.setCaloriesIdle(caloriesIdle);
        n.timestampLastUpdate();
        dateLogRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<DateLog> getAllUsers() {
        // This returns a JSON or XML with the users
        return dateLogRepository.findAll();
    }
}
