package com.CS5500.springbootinfrastructure.controller;

import com.CS5500.springbootinfrastructure.dao.Activity;
import com.CS5500.springbootinfrastructure.dao.DateLog;
import com.CS5500.springbootinfrastructure.dao.Move;
import com.CS5500.springbootinfrastructure.repos.*;
import java.time.LocalDate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.sql.Date;
import java.util.List;
import java.util.Map;

@Controller // This means that this class is a Controller
@RequestMapping(path="/activitydb") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private DateLogRepository dateLogRepository;
    private ActivityRepository activityRepository;
    private MoveRepository moveRepository;
    private PlaceRepository placeRepository;
    private TypeRepository typeRepository;

    @PostMapping(path="/dateLog") // Map ONLY POST Requests
    public @ResponseBody
    String addNewDateLog (@RequestParam Integer caloriesIdle) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        DateLog n = new DateLog();

        n.setDate(new Date(System.currentTimeMillis()));
        n.setCaloriesIdle(caloriesIdle);
        n.timestampLastUpdate();
        dateLogRepository.save(n);
        return "Saved";
    }
    @GetMapping(path = "/dateLog")
    public @ResponseBody
    Iterable<Map<String, Object>> getAllDates() {
        // This returns a JSON or XML with the users
        List<Map<String, Object>> data = dateLogRepository.getJSONDates();
        return data;
    }

/*    @GetMapping(path = "/dateLog/{id}")
    public @ResponseBody
    DateLog getDate(@PathVariable Integer id) {
        // This returns a JSON or XML with the users
        List<Map<String, Object>> data = dateLogRepository.getJSONDates();
        return data;
    }*/

    @GetMapping(path = "/activity")
    public @ResponseBody
    Iterable<Map<String, Object>> getAllActivity() {
        return dateLogRepository.getJSONActivities();
    }
    @GetMapping(path = "/move")
    public @ResponseBody
    Iterable<Map<String, Object>> getAllMove() {
        return dateLogRepository.getJSONMoves();
    }

    @GetMapping(path = "/type")
    public @ResponseBody
    Iterable<Map<String, Object>> getAllType() {
        return dateLogRepository.getJSONTypes();
    }

    @GetMapping(path = "/place")
    public @ResponseBody
    Iterable<Map<String, Object>> getAllPlace() {
        return dateLogRepository.getJSONPlaces();
    }

}
